### ISSUE TITLE
Submit a New Tournament

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/hockey-mvp#1]
### Story
**As a user, I want to submit a new tournament so that it can be listed for reviews.**

#### Description
Build a submission form for users to submit new tournaments. The form should include the following fields:

- Tournament Name
- Location
- Date
- Contact Information
- Additional Notes

#### Tasks
- [x] Design the form layout
- [x] Implement frontend validation
- [x] #10
- [x] Connect to backend service
- [x] Test form submissions
- [x] Create unit tests

**Comment by reyesjl** [comment]
## Here are some updates: 

@jamesli898 check it out

![Screenshot 2024-10-31 161740](https://github.com/user-attachments/assets/0a31fcf0-78b0-4342-923e-e1ebd29348a8)
![Screenshot 2024-10-31 161617](https://github.com/user-attachments/assets/cea1921a-03ba-4d1e-bf58-5b98cfdbc14f)
![Screenshot 2024-10-31 161657](https://github.com/user-attachments/assets/8ed8f1ee-1290-4408-9414-7a8325754a4a)
![Screenshot 2024-10-31 161713](https://github.com/user-attachments/assets/fbbe3ba2-c7d0-4657-b516-f13c522392cc)

**Comment by reyesjl** [comment]
new updates :) @jamesli898

![Screenshot 2024-11-05 115222](https://github.com/user-attachments/assets/486214f6-3805-470f-b104-4d57eb64d875)
![Screenshot 2024-11-05 141846](https://github.com/user-attachments/assets/7a34f5e6-9be4-4dc9-bf3b-ece8859b3481)
![Screenshot 2024-11-05 141649](https://github.com/user-attachments/assets/68951804-1bb3-4f69-bdf5-4ec18ce90323)
![Screenshot 2024-11-05 141748](https://github.com/user-attachments/assets/20a3f9c2-81f0-446b-b109-40709e62f288)

**Comment by reyesjl** [comment]
Form updated:
![Screenshot 2024-11-06 140742](https://github.com/user-attachments/assets/38badc14-f8a9-4c34-9283-303af0df718a)
![Screenshot 2024-11-06 140806](https://github.com/user-attachments/assets/0117cb3c-05a3-4f64-88a1-5fde19bdaae3)
