### ISSUE TITLE
View Tournaments and Reviews

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/hockey-mvp#4]
### Story
**As a user, I want to view a list of tournaments and their reviews so that I can make informed decisions.**

#### Description
Develop a user interface where users can view a list of tournaments along with associated reviews. Users should be able to click on each tournament for more details.

#### Tasks
- [x] Design the tournament listing page
- [x] Implement functionality to fetch and display tournaments
- [x] Include review snippets for each tournament
- [x] Create a detailed view for each tournament with full reviews
- [x] Create unit tests for the tournament display functionality
