### ISSUE TITLE
Project Inititialization

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/hockey-mvp#6]
### Story
**As a developer, I want to initialize the project structure so that I can set up the application environment.**

#### Description
Set up the initial project structure for the Hockey Tournament Review App. This includes creating the necessary files, directories, and configurations for both the frontend and backend.

#### Tasks
- [x] Create a GitHub repository for the project
- [x] Set up the frontend framework (e.g., React, Vue, or Angular)
- [x] Set up the backend framework (e.g., Node.js, Django, or Flask)
- [x] Configure the database (e.g., Firebase, MongoDB, or PostgreSQL)
- [x] Create a basic README file with project details
- [x] Set up version control with Git
- [x] Configure environment variables and project settings

**Comment by reyesjl** [comment]
I have create a basic app using express js and mongo DB, leaning toward using the MERN stack to develop a robust web app that will handle updates well.

I was able to deploy it locally and establish a connection to the database as well as implement a simple tournament submit route and some error handling. **_This is just the backend setup, no frontend at all._**

Good start. Enjoy some pics. Goodnite.

![Screenshot 2024-10-29 213218](https://github.com/user-attachments/assets/ee9e884f-d94d-4e6c-8a01-b076f0273cc7)
![Screenshot 2024-10-29 213231](https://github.com/user-attachments/assets/877d4e79-c8a2-4d38-977d-52b8031b47fa)

**Comment by reyesjl** [comment]
The API has been developed to accept the following:

1. create a tournament
2. view, update, or delete by tournament id
3. list all tournaments

The API supports all of these functions and was tested using POSTMAN. I added some fake tournaments and can view them in mongoDB now. 

Next I will focus on getting a simple frontend deployed in Vue.js or Next.js to work with what we've got to aid in submissions and testing for that. Building out forms, etc.

**Comment by reyesjl** [comment]
Setup a frontend using vue.js and tailwind.css, little bit of a learning curve here, but can count on it being modular and flexible down the road. It is also very well documented.

Have a look at the home page:

![Screenshot 2024-10-30 220048](https://github.com/user-attachments/assets/58982f59-9a74-4d13-a3e8-474af238f27f)
